---
- name: Add Users to Group and Grant sudo Permissions
  hosts: all
  become_user: root

  vars:
    users:
      - user1
      - user2  # Add more usernames as needed
    target_group: adm

  tasks:
    - name: Create group if it doesn't exist
      ansible.builtin.group:
        name: "{{ target_group }}"
        state: present

    - name: Add users to the group
      ansible.builtin.user:
        name: "{{ item }}"
        groups: "{{ target_group }}"
        append: yes
      loop: "{{ users }}"
      loop_control:
        loop_var: item

    - name: Grant sudo permissions (RHEL specific)
      ansible.builtin.copy:
        content: "{{ item }} ALL=(ALL:ALL) ALL"
        dest: "/etc/sudoers.d/{{ item }}"
        mode: 0440
      when: ansible_distribution == 'Red Hat'
      loop: "{{ users }}"
      loop_control:
        loop_var: item

    - name: Grant sudo permissions (Ubuntu specific)
      ansible.builtin.lineinfile:
        dest: /etc/sudoers
        line: "{{ item }} ALL=(ALL:ALL) ALL"
        validate: 'visudo -cf %s'
      when: ansible_distribution == 'Ubuntu'
      loop: "{{ users }}"
