---
- name: Set Password Policy for Users
  hosts: all
  become: true

  vars:
    users_password_policy:
      - username: user1
        max_password_age_days: 60
        min_password_age_days: 7
        min_password_length: 8
        password_complexity: 1
      - username: user2
        max_password_age_days: 90
        min_password_age_days: 10
        min_password_length: 10
        password_complexity: 1
      - username: user3
        max_password_age_days: 120
        min_password_age_days: 14
        min_password_length: 12
        password_complexity: 1

  tasks:
    - name: Set Password Policy for RHEL
      ansible.builtin.user:
        name: "{{ item.username }}"
        update_password: on_create
      with_items: "{{ users_password_policy }}"
      when: "'RedHat' in ansible_distribution"

    - name: Set Password Policy for Ubuntu
      ansible.builtin.user:
        name: "{{ item.username }}"
        update_password: on_create
      with_items: "{{ users_password_policy }}"
      when: "'Ubuntu' in ansible_distribution"


